#!/bin/sh

function finish {
    rm ~/.side/session-$XDG_SESSION_ID
}

if [ $1 == "-f" ]; then
    trap finish EXIT
    
    . $2 
    if [ ! -d ~/.side ]; then
        mkdir ~/.side
    fi
    echo $$ > ~/.side/session-$XDG_SESSION_ID

    while true; do
        sleep 1
    done
fi

if [[ ! $1 ]]; then
    echo "(SiDE): ERROR: No window manager specified"
    exit
fi

if [[ -f ~/.${1}initrc ]]; then
    exec dbus-launch --exit-with-session side-session -f ~/.${1}initrc
elif [[ -f /etc/side-session/${1}initrc ]]; then
    exec dbus-launch --exit-with-session side-session -f /etc/side-session/.${1}initrc
else
    echo "(SiDE) ERROR: $1 is not a window manager"
fi
